[package]
name = "vmp-rewriter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vmp-core.workspace = true
vmp-loader.workspace = true
vmp-stub.workspace = true
goblin.workspace = true
byteorder.workspace = true
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
vmp-isa = { path = "../vmp-isa" }
